services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: smashuser
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: smashdb
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smashuser -d smashdb"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:
